# Generated by Django 6.1.1 on 2026-09-15 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_department'),
        ('medical_records', '0001_initial'),
        ('patients', '0003_alter_patients_created_at_alter_patients_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='medical_notes',
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='disease',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='temperature',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_medical_records', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_medical_records', to='patients.patients'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='record_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True),
        ),
    ]
