# Generated by Django 6.1.1 on 2026-09-14 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        ('patients', '0003_alter_patients_created_at_alter_patients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_name', models.CharField(max_length=255)),
                ('test_result', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=30)),
                ('test_date', models.DateField(auto_now_add=True)),
                ('technician_notes', models.TextField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laboratory_tests', to='patients.patients')),
            ],
        ),
    ]
