# Generated by Django 6.1.1 on 2026-09-15 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_department'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_given', to='doctors.doctor'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(help_text='Example: 1 tablet', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(help_text='Example: 5 days', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(help_text='Example: Twice a day', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescribed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
