# Generated by Django 6.1.1 on 2026-09-14 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0003_alter_patients_created_at_alter_patients_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.AutoField(primary_key=True, serialize=False)),
                ('bed_number', models.CharField(max_length=50, unique=True)),
                ('room_number', models.CharField(max_length=50)),
                ('ward_name', models.CharField(max_length=100)),
                ('bed_type', models.CharField(choices=[('General', 'General'), ('Semi-Private', 'Semi-Private'), ('Private', 'Private'), ('ICU', 'ICU'), ('Emergency', 'Emergency')], default='General', max_length=30)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Maintenance')], default='Available', max_length=30)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_beds', to='patients.patients')),
            ],
        ),
    ]
