# Generated by Django 6.1.1 on 2026-09-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patients',
            options={},
        ),
    ]
