# Generated by Django 6.1.1 on 2026-09-14 15:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patients',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
