# Generated by Django 6.1.1 on 2026-09-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='availability_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability_start',
            field=models.TimeField(default='09:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
